title: PlayPI
description: A local API testing playground for RESTful, gRPC, GraphQL, and WebSocket APIs.
baseurl: "/PlayPI" # Update this to match your repository name
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
