name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run automated tests
        run: |
          chmod +x services/graphql/inventory_management/run_tests.sh
          ./services/graphql/inventory_management/run_tests.sh
          chmod +x services/grpc/inventory_management/run_tests.sh
          ./services/grpc/inventory_management/run_tests.sh
          chmod +x services/grpc/user_registration/run_tests.sh
          ./services/grpc/user_registration/run_tests.sh
          chmod +x services/restful/inventory_management/run_tests.sh
          ./services/restful/inventory_management/run_tests.sh
          chmod +x services/restful/task_management/run_tests.sh
          ./services/restful/task_management/run_tests.sh
          chmod +x services/websocket/live_chat/run_tests.sh
          ./services/websocket/live_chat/run_tests.sh